default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: robot_development

test:
  <<: *default
  database: robot_test

production:
  <<: *default
  database: robot_production
  username: robot
  password: <%= ENV['ROBOT_DATABASE_PASSWORD'] %>
